type User @table {
  email: String!
  displayName: String!
  createdAt: Timestamp!
  role: String!
  phoneNumber: String
  photoUrl: String
}

type Service @table {
  esthetician: User!
  name: String!
  price: Float!
  durationMinutes: Int!
  createdAt: Timestamp!
  description: String
  imageUrl: String
}

type Appointment @table {
  client: User!
  esthetician: User!
  service: Service!
  appointmentDate: Date!
  startTime: String!
  endTime: String!
  status: String!
  createdAt: Timestamp!
  clientNotes: String
  estheticianNotes: String
}

type Payment @table {
  client: User!
  appointment: Appointment!
  amount: Float!
  currency: String!
  paymentDate: Timestamp!
  transactionId: String!
  status: String!
  createdAt: Timestamp!
  paymentMethod: String
}

type Conversation @table {
  client: User!
  createdAt: Timestamp!
  lastUpdatedAt: Timestamp!
  topic: String
}

type Message @table {
  conversation: Conversation!
  client: User!
  content: String!
  sender: String!
  timestamp: Timestamp!
}